name: release_and_push

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'New version/tag to generate'
        required: true

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate the given release in GitHub
        env:
          TAG: ${{ github.event.inputs.tag }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions
        run: make release

  push_docker:
    name: Push Docker image
    needs: release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push Docker image
        env:
          TAG: ${{ github.event.inputs.tag }}
        run: make docker-push
